global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'api'
    static_configs:
      - targets: ['mtaadao-api:4000']

  - job_name: 'frontend'
    metrics_path: /metrics
    static_configs:
      - targets: ['mtaadao-frontend:80']
