const fs = require('fs');
const path = require('path');

const exts = new Set(['.ts','.js','.tsx','.jsx','.py','.sh','.rs','.sol','.java','.go','.json']);
const skipDirs = new Set(['node_modules','.git','dist','artifacts','build','.next','.venv','venv']);
const cwd = process.cwd();

const staticKeys = new Set();
const dynamicPatterns = new Set();

function walk(dir) {
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch (e) {
    return;
  }
  for (const e of entries) {
    if (e.isDirectory()) {
      if (skipDirs.has(e.name)) continue;
      walk(path.join(dir, e.name));
    } else if (e.isFile()) {
      const ext = path.extname(e.name).toLowerCase();
      if (!exts.has(ext)) continue;
      const fp = path.join(dir, e.name);
      let s;
      try {
        s = fs.readFileSync(fp, 'utf8');
      } catch (err) {
        continue;
      }
      let m;
      const dotRegex = /process\.env\.([A-Za-z0-9_]+)/g;
      while ((m = dotRegex.exec(s)) !== null) {
        staticKeys.add(m[1]);
      }
      const bracketRegex = /process\.env\[['\"]([A-Za-z0-9_]+)['\"]\]/g;
      while ((m = bracketRegex.exec(s)) !== null) {
        staticKeys.add(m[1]);
      }
      const templateRegex = /process\.env\[`([^`]+)`\]/g;
      while ((m = templateRegex.exec(s)) !== null) {
        const content = m[1];
        if (!content.includes('${')) {
          staticKeys.add(content);
        } else {
          dynamicPatterns.add(content);
        }
      }
    }
  }
}

walk(cwd);

const keys = Array.from(staticKeys).sort((a,b)=>a.localeCompare(b));
fs.writeFileSync(path.join(cwd,'env_keys.txt'), keys.join('\n') + '\n', 'utf8');

const exampleLines = [];
exampleLines.push('# .env.example - generated by scripts/extract_env_keys.js');
exampleLines.push('# Fill in required secret values. Do not commit real secrets.');
exampleLines.push('');

for (const k of keys) {
  let placeholder = '';
  const lk = k.toLowerCase();
  if (lk.includes('key') || lk.includes('secret') || k.includes('PRIVATE') || lk.includes('password') || lk.includes('token') || lk.includes('jwt')) {
    placeholder = 'REPLACE_WITH_SECRET';
  } else if (k.includes('PORT')) {
    placeholder = '5000';
  } else if (lk.includes('url') || lk.includes('rpc') || lk.includes('endpoint')) {
    placeholder = 'http://localhost:8545';
  } else if (lk.includes('database') || lk.includes('database_url') || k === 'DATABASE_URL') {
    placeholder = 'postgresql://postgres:postgres@localhost:5432/mtaadao';
  }
  exampleLines.push(`${k}=${placeholder}`);
}

if (dynamicPatterns.size) {
  exampleLines.push('');
  exampleLines.push('# Dynamic env patterns detected (templates containing ${...}):');
  for (const p of Array.from(dynamicPatterns).sort()) {
    exampleLines.push(`# pattern: ${p}`);
  }
}

fs.writeFileSync(path.join(cwd,'.env.example'), exampleLines.join('\n') + '\n', 'utf8');

console.log(`Wrote env_keys.txt (${keys.length} keys) and .env.example (with placeholders).`);
if (dynamicPatterns.size) {
  console.log(`Detected ${dynamicPatterns.size} dynamic patterns (listed in .env.example).`);
}
